apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-deployment-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

# Added for retrieving the nodes:
- apiGroups: [""]
  resources:
  - nodes
  verbs:
  - get
  - list