# permissions for end users to view myresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multi-deployment
    app.kubernetes.io/managed-by: kustomize
  name: myresource-viewer-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - myresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.example.com
  resources:
  - myresources/status
  verbs:
  - get
