---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - myresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - myresources/finalizers
  verbs:
  - update
- apiGroups:
  - app.example.com
  resources:
  - myresources/status
  verbs:
  - get
  - patch
  - update

# I have added this permissions:
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   verbs:
#   - get
#   - list
#   - watch
#   - create
#   - update
#   - patch
#   - delete
